name: "Deploy App"

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Frontend
        working-directory: todo-frontend
        run: |
          npm install
          npm run build

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: todo-frontend/static

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22' # must match the version in the pom.xml
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: todo-backend-0.0.1-SNAPSHOT.jar
          path: target/todo-backend-0.0.1-SNAPSHOT.jar

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download backend build artifact
        uses: actions/download-artifact@v4
        with:
          name: todo-backend-0.0.1-SNAPSHOT.jar
          path: target/todo-backend-0.0.1-SNAPSHOT.jar

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}

  deploy:
    name: deploy-to-render
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    environment:
      name: Todo-Backend
      url: https://todo-backend-todo.onrender.com
    steps:
      - name: Trigger Render.com Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY }}
